<a href="https://colab.research.google.com/github/manutd-1878/Data-Science-Bootcamp/blob/main/01_wprowadzenie/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
pd.__version__

'2.2.2'

# **Podstawowe struktury danych: pd.Series**

In [3]:
s = pd.Series(data=[3, 2, 4, 6])
s

0    3
1    2
2    4
3    6
dtype: int64

In [8]:
s = pd.Series(data=[3, 2, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3
b    2
c    4
d    6
Name: sample, dtype: int64

In [9]:
s = pd.Series(data=[3., 2, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

In [11]:
import numpy as np
s = pd.Series(data=[3., np.nan, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [12]:
s = pd.Series(data=[True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [13]:
s = pd.Series(data=np.arange(10, 20), index=pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [14]:
s = pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [15]:
type(s)

pandas.core.series.Series

In [16]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
s = pd.Series(data=np.arange(10, 20), index=pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [18]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [19]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [20]:
s = pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [21]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
s.values

array(['python', 'java', 'sql'], dtype=object)

In [23]:
s.dtypes

dtype('O')

In [24]:
s.shape

(3,)

In [25]:
price = pd.Series(data={'Apple': 200, 'CD Projekt': 60, 'Amazon': 1900, 'KGHM': np.nan})
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [26]:
price['CD Projekt']

np.float64(60.0)

In [28]:
price.iloc[1]

np.float64(60.0)

In [29]:
price.count()

np.int64(3)

In [39]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [31]:
price.sum()

np.float64(2160.0)

In [32]:
price.max()

1900.0

In [33]:
price.min()

60.0

In [37]:
round(price.std(), 3)

1024.305

In [38]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [41]:
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [43]:
price.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [44]:
price.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [45]:
price.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [46]:
price.sort_values(ascending=False)

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [49]:
price_pln = price.apply(lambda x: x * 3.8) # konwertujemy z $ na PLN

In [50]:
price_pln

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

In [52]:
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

# **Podstawowe struktury danych: pd.DataFrame**

In [5]:
df = pd.DataFrame(data=[12, 12, 32])
df

    0
0  12
1  12
2  32

In [6]:
df = pd.DataFrame(data=[12, 12, 32], index=['first', 'second', 'third'], columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [7]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [8]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [9]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [10]:
df.index

Index(['first', 'second'], dtype='object')

In [11]:
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [13]:
df.describe()

           col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [14]:
df.describe().T

       count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

# **Selekcja kolumn**

In [15]:
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [16]:
df['col_1']

first     10
second    23
Name: col_1, dtype: int64

In [17]:
type(df['col_1'])

pandas.core.series.Series

In [18]:
df[['col_1']]

        col_1
first      10
second     23

In [19]:
type(df[['col_1']])

pandas.core.frame.DataFrame

In [20]:
df.columns = ['col_1', 'col_2', 'col_3']
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [21]:
df.columns = ['a', 'sprzedaz_grudzien', 'c']
df

         a  sprzedaz_grudzien   c
first   10                 12  13
second  23                 12  10

In [22]:
df.sprzedaz_grudzien

first     12
second    12
Name: sprzedaz_grudzien, dtype: int64

In [24]:
df['d'] = df.a + df.c # dodanie kolmny d
df

         a  sprzedaz_grudzien   c   d
first   10                 12  13  23
second  23                 12  10  33

In [25]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [26]:
df.loc['first'] # wycinanie obiektów (danych) po nazwie

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [27]:
df.loc['first', 'col_2']

np.int64(12)

In [31]:
df.loc[:, 'col_2']

first     12
second    12
Name: col_2, dtype: int64

In [30]:
df.iloc[0] # iloc do wycinania po liczbie

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [32]:
df.iloc[0, 1]

np.int64(12)